### ISSUE TITLE
Schnittstellen FE/BE

### ISSUE THREAD

**Issue by nhett** [Umweltrechner-HSRM/backend#17]

**Comment by kinaIen** [comment]
Das Frontend benötigt eine (dynamische) Liste aller Variabelnamen, die der User im Formeleditor zur Auswahl angezeigt bekommt. Es ist zu definieren, wie die eingegebene Formel wieder ans Backend geliefert wird. Dort ist sie zu interpretieren und der neu berechnete Wert muss zur Auswahl für die Anlage von Linecharts/Balkendiagrammen etc. wieder im Frontend zur Verfügung stehen. Die Formel darf bei Absturz des Systems nicht verloren gehen.
